services:
  app:
    build: .
    container_name: my_nestjs_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PG_HOST=db
      - PG_TYPE=postgres
      - PG_PORT=5432
      - PG_USERNAME=myuser
      - PG_PASSWORD=mypassword
      - PG_DATABASE=mydatabase
      - PORT=3000

  db:
    image: postgres:15-alpine
    container_name: my_postgres_db
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
